### ISSUE TITLE
Gnat2goto assertions are misinterpreted by CBMC

### ISSUE THREAD

**Issue by xbauch** [diffblue/gnat2goto#85]
```
procedure Divide is
  a : Integer := 11;
  b : Integer := 22;
  c : Integer;
begin
  c := a + b;
  pragma Assert (c = 33);
  pragma Assert (True);
end;
```
Both assertions are correctly translated on the GOTO level. On the SSA level, the first assertion is translated to `ASSERT(FALSE)` and the second to `ASSERT(standard__boolean__true!0#0)`. Both assertions fail when CBMC tries to verify them.

**Comment by hannes-steffenhagen-diffblue** [comment]
Note this requires https://github.com/diffblue/gnat2goto/pull/71 to work at all at the moment

**Comment by hannes-steffenhagen-diffblue** [comment]
I believe this is actually not a problem with assertions after all - rather, it seems like it was an issue of how CBMC does equality checking.

https://github.com/diffblue/gnat2goto/pull/89 should fix the first one. The second assert is actually broken because we handle true/false incorrectly, I think I know how to fix it though.

**Comment by martin-cs** [comment]
@xbauch : I'm probably being stupid but why is this now OK?  A link to what fixed it / these added as now-passing test cases would be fine.
